version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: '_'
    groups:
      dev-minor-versions:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      prod-minor-versions:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '_'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '_'
