apiVersion: v1
appVersion: "1.0"
description: Generic Helm Chart for deploying a single tier Nextjs application
name: passport-status
version: 0.1.0
maintainers:
  - name: Digital Technology Solutions, Site Reliability Engineering
    email: gocmts@gmail.com
    url: https://confluence.dts-stn.com/display/OPS/Site+Reliability+Engineering
