#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# https://github.com/okonet/lint-staged/issues/1164
if sh -c ": >/dev/tty" >/dev/null 2>/dev/null; then
exec >/dev/tty 2>&1
elif sh -c ": >/dev/console" >/dev/null 2>/dev/null; then
exec >/dev/console 2>&1
elif sh -c ": >/dev/tty0" >/dev/null 2>/dev/null; then
exec >/dev/tty0 2>&1
fi

npx lint-staged
