name: Dynamic Application Security Tests

on:  
  schedule:
    - cron: '0 0 * * 0'

jobs:
  zap-proxy-scan:
    name: ZAP Proxy Test
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP FULL Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "https://passport-status-main.dev-rhp.dts-stn.com/"
          fail_action: "false"
          token: ${{ secrets.GITHUB_TOKEN }}
